# Generated by Django 4.2 on 2023-12-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('emty_seat', models.IntegerField()),
                ('start', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
            ],
        ),
    ]
