# Generated by Django 4.2 on 2023-12-30 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('no', models.IntegerField()),
                ('city', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=25)),
                ('ticket_number', models.CharField(max_length=25)),
                ('price', models.FloatField()),
                ('emty_seat', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.terminal')),
            ],
        ),
    ]
